let name="Aayush";
let surname="Trivedi";
console.log(23+97);
console.log(32+97);
console.log(23+79);
console.log(29+97);
console.log(23+37);
console.log((4+6+9)/77);
let a=10;
console.log(a);
a=12;
console.log(a);
a=10;
console.log(a);
let b=7*a;
console.log(b);
const max=57;
const actual=max-13;
const percentage=actual/max;
console.log(percentage)
console.log(max===-max-0);